name: Docker-in-Docker Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:

jobs:
  dind-job:
    runs-on: [self-hosted, dind]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Check Docker Version
        run: docker version

      - name: Build Docker Image
        run: |
          docker build -t curl-action .
        working-directory: ./actions/curl-action
        
      - name: Run Ping Action
        uses: ./actions/curl-action
        with:
          url: https://www.google.com
