name: Docker-in-Docker Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:

jobs:
  dind-job:
    runs-on: [self-hosted, dind]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Check Docker Version
        run: docker version
        
      - name: Run Ping Action
        uses: ./actions/ping-action
        with:
          host: google.com
          count: 3
