name: Docker-in-Docker Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: [self-hosted, dind]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Check Docker Version
        run: docker version
        
      # - name: Display GitHub Context
      #   run: echo "This workflow was triggered by ${{ github.actor }} on ${{ github.event_name }} event."