name: Hello World Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Say Hello
        run: echo "Hello, World! This is a GitHub Actions demo."
        
      - name: Display GitHub Context
        run: echo "This workflow was triggered by ${{ github.actor }} on ${{ github.event_name }} event."